// ============================================================
// BUDAK LAB — Member Roster
// ============================================================
// gender: 'm' | 'f'  (drives figure silhouette — hijab vs. short hair)
// theme:  accent color key, maps to CSS custom properties in style.css
// status: 'current' | 'alumni'
// ============================================================

const MEMBERS = [
  {
    id: "en.zainal",
    domain: "engineering",
    order: 0,
    gender: "m",
    isLeader: true,
    name: "Encik Zainal Abidin",
    role: "Founder & Lead Engineer",
    theme: "blue",
    joined: 2022,
    left: null,
    status: "current",
    bio: "Started BUDAK LAB in a second-year dorm room with a shared GitHub repo and too much coffee. Still writes more backend code than a founder probably should.",
    skills: [
      { name: "Systems Architecture", level: 92 },
      { name: "Backend Engineering", level: 95 },
      { name: "Team Leadership", level: 88 },
      { name: "Cloud Infrastructure", level: 84 },
    ],
    contribution: { leadership: 96, project: 90, technical: 92, innovation: 87, collaboration: 91 },
    projects: ["gis-flood", "dashboard-ops"],
  },
  {
    id: "aisyah",
    domain: "ai",
    order: 1,
    gender: "f",
    isLeader: false,
    name: "Nur Aisyah",
    role: "AI Research Lead",
    theme: "purple",
    joined: 2022,
    left: null,
    status: "current",
    bio: "Turns papers nobody wants to read into models the rest of the lab can actually ship. Currently obsessed with lightweight vision models for low-power devices.",
    skills: [
      { name: "Machine Learning", level: 94 },
      { name: "Computer Vision", level: 89 },
      { name: "Python / PyTorch", level: 93 },
      { name: "Research Writing", level: 81 },
    ],
    contribution: { leadership: 78, project: 91, technical: 94, innovation: 95, collaboration: 84 },
    projects: ["ai-crop", "ai-vision"],
  },
  {
    id: "zahra",
    domain: "gis",
    order: 2,
    gender: "f",
    isLeader: false,
    name: "Siti Zahra",
    role: "GIS & Spatial Analyst",
    theme: "emerald",
    joined: 2022,
    left: 2025,
    status: "alumni",
    bio: "Mapped half the campus flood zones before graduating. Now works in urban planning, but still reviews the lab's GIS pull requests on weekends.",
    skills: [
      { name: "GIS / QGIS", level: 90 },
      { name: "Spatial Modeling", level: 86 },
      { name: "Remote Sensing", level: 79 },
      { name: "Data Visualization", level: 83 },
    ],
    contribution: { leadership: 70, project: 88, technical: 85, innovation: 80, collaboration: 89 },
    projects: ["gis-flood"],
  },
  {
    id: "humaira",
    domain: "frontend",
    order: 3,
    gender: "f",
    isLeader: false,
    name: "Humaira Rasyid",
    role: "Frontend Developer",
    theme: "orange",
    joined: 2023,
    left: null,
    status: "current",
    bio: "The reason the lab's tools stopped looking like spreadsheets. Cares more about motion easing curves than most people care about anything.",
    skills: [
      { name: "JavaScript / GSAP", level: 91 },
      { name: "UI Engineering", level: 93 },
      { name: "Design Systems", level: 87 },
      { name: "Accessibility", level: 80 },
    ],
    contribution: { leadership: 65, project: 90, technical: 89, innovation: 84, collaboration: 92 },
    projects: ["dashboard-ops", "web-portal"],
  },
  {
    id: "khadijah",
    domain: "data",
    order: 4,
    gender: "f",
    isLeader: false,
    name: "Khadijah Putri",
    role: "Data Analyst",
    theme: "rose",
    joined: 2023,
    left: null,
    status: "current",
    bio: "Finds the one broken row in a 40,000-line dataset without breaking a sweat. Believes a chart should never need a caption to be understood.",
    skills: [
      { name: "Data Analytics", level: 92 },
      { name: "SQL / ETL", level: 88 },
      { name: "Statistical Modeling", level: 83 },
      { name: "Dashboarding", level: 90 },
    ],
    contribution: { leadership: 62, project: 87, technical: 90, innovation: 78, collaboration: 85 },
    projects: ["dashboard-ops"],
  },
  {
    id: "fatimah",
    domain: "research",
    order: 5,
    gender: "f",
    isLeader: false,
    name: "Fatimah Nabila",
    role: "UX Researcher",
    theme: "cyan",
    joined: 2023,
    left: 2025,
    status: "alumni",
    bio: "Interviewed more campus staff than the student union did. Left the lab having reshaped how every project starts — with users, not features.",
    skills: [
      { name: "User Research", level: 90 },
      { name: "Usability Testing", level: 86 },
      { name: "Prototyping", level: 79 },
      { name: "Facilitation", level: 88 },
    ],
    contribution: { leadership: 74, project: 82, technical: 71, innovation: 85, collaboration: 93 },
    projects: ["web-portal"],
  },
  {
    id: "raihanah",
    domain: "backend",
    order: 6,
    gender: "f",
    isLeader: false,
    name: "Raihanah Yusof",
    role: "Backend Developer",
    theme: "amber",
    joined: 2023,
    left: null,
    status: "current",
    bio: "Keeps the APIs the rest of the lab depends on boring, fast, and well-documented — which, in her words, is the highest compliment a backend can get.",
    skills: [
      { name: "Node.js / APIs", level: 89 },
      { name: "Database Design", level: 85 },
      { name: "DevOps", level: 78 },
      { name: "Testing", level: 82 },
    ],
    contribution: { leadership: 68, project: 86, technical: 90, innovation: 76, collaboration: 83 },
    projects: ["ai-crop", "web-portal"],
  },
  {
    id: "syahidah",
    domain: "research",
    order: 7,
    gender: "f",
    isLeader: false,
    name: "Syahidah Malik",
    role: "Research & Documentation",
    theme: "teal",
    joined: 2024,
    left: null,
    status: "current",
    bio: "Writes the papers, grant applications and READMEs that actually get read. The lab's institutional memory, in the best possible sense.",
    skills: [
      { name: "Technical Writing", level: 91 },
      { name: "Academic Research", level: 88 },
      { name: "Grant Writing", level: 80 },
      { name: "Editing", level: 85 },
    ],
    contribution: { leadership: 60, project: 79, technical: 68, innovation: 74, collaboration: 90 },
    projects: ["ai-vision"],
  },
  {
    id: "syahidah",
    domain: "research",
    order: 7,
    gender: "f",
    isLeader: false,
    name: "Syahidah Malik",
    role: "Research & Documentation",
    theme: "teal",
    joined: 2024,
    left: null,
    status: "current",
    bio: "Writes the papers, grant applications and READMEs that actually get read. The lab's institutional memory, in the best possible sense.",
    skills: [
      { name: "Technical Writing", level: 91 },
      { name: "Academic Research", level: 88 },
      { name: "Grant Writing", level: 80 },
      { name: "Editing", level: 85 },
    ],
    contribution: { leadership: 60, project: 79, technical: 68, innovation: 74, collaboration: 90 },
    projects: ["ai-vision"],
  },
];

// ============================================================
// The Reel — project categories shown as the page 2 montage.
// Drop matching photos into assets/projects/ using the `image`
// filename below. If a file is missing, the reel falls back to
// a themed icon tile automatically — nothing breaks.
// ============================================================
const REEL_ITEMS = [
  { id: "dashboard", title: "Dashboards", desc: "Live ops metrics for the whole lab.", icon: "▦", theme: "blue", image: "assets/projects/dashboard.jpg" },
  { id: "gis", title: "GIS", desc: "Spatial risk mapping & remote sensing.", icon: "◈", theme: "emerald", image: "assets/projects/gis.jpg" },
  { id: "ai", title: "Artificial Intelligence", desc: "Lightweight models, real deployments.", icon: "◎", theme: "purple", image: "assets/projects/ai.jpg" },
  { id: "web", title: "Website Development", desc: "Portals that connect students to funding.", icon: "◫", theme: "orange", image: "assets/projects/web.jpg" },
  { id: "data", title: "Data Analytics", desc: "Turning raw exports into decisions.", icon: "▤", theme: "rose", image: "assets/projects/data.jpg" },
  { id: "research", title: "Research", desc: "Papers, grants, documentation.", icon: "▥", theme: "teal", image: "assets/projects/research.jpg" },
  { id: "achievements", title: "Achievements", desc: "Recognition from beyond campus.", icon: "★", theme: "amber", image: "assets/projects/achievements.jpg" },
];

const PROJECTS = {
  "gis-flood": {
    id: "gis-flood",
    title: "FloodWatch GIS",
    category: "GIS",
    theme: "emerald",
    summary: "Real-time flood risk mapping for the campus catchment area.",
    overview: "A spatial monitoring platform combining rainfall telemetry with campus elevation data to flag flood-prone routes before storms hit.",
    problem: "Campus facilities had no early-warning system for the low-lying routes that flood every monsoon season, leading to last-minute closures.",
    solution: "Built a QGIS-backed pipeline feeding a live web map, with automated alerts triggered at set rainfall thresholds.",
    stack: ["QGIS", "PostGIS", "Python", "Leaflet", "Node.js"],
  },
  "dashboard-ops": {
    id: "dashboard-ops",
    title: "Lab Ops Dashboard",
    category: "Dashboard",
    theme: "blue",
    summary: "Internal dashboard tracking every project, deadline and dataset across the lab.",
    overview: "A single pane of glass for the lab's own operations — project status, dataset freshness, and upcoming deadlines.",
    problem: "Project status lived across five different spreadsheets that were perpetually out of sync.",
    solution: "Centralized ingestion from the lab's tools into one dashboard with role-based views for members and advisors.",
    stack: ["React-free JS", "Node.js", "PostgreSQL", "Chart.js"],
  },
  "ai-crop": {
    id: "ai-crop",
    title: "CropSense AI",
    category: "Artificial Intelligence",
    theme: "purple",
    summary: "A lightweight vision model that detects crop stress from phone photos.",
    overview: "An on-device model helping smallholder farmers near campus spot early signs of crop stress without lab equipment.",
    problem: "Diagnostic tools for early crop stress required equipment far outside a smallholder farmer's budget.",
    solution: "Trained a compact vision model that runs directly on a mid-range phone, no connectivity required.",
    stack: ["PyTorch", "TensorFlow Lite", "Python", "Android"],
  },
  "web-portal": {
    id: "web-portal",
    title: "Student Innovation Portal",
    category: "Website Development",
    theme: "orange",
    summary: "A campus-wide portal connecting student researchers with funding and mentors.",
    overview: "A matchmaking platform pairing early-stage student projects with faculty mentors and micro-grants.",
    problem: "Promising student projects were stalling for lack of a mentor or a few hundred dollars in funding.",
    solution: "Shipped a lightweight portal listing open mentorships and micro-grants, with a two-click application flow.",
    stack: ["HTML/CSS/JS", "GSAP", "Node.js", "MongoDB"],
  },
  "ai-vision": {
    id: "ai-vision",
    title: "AccessLens",
    category: "Artificial Intelligence",
    theme: "teal",
    summary: "A vision-to-speech tool aiding navigation for visually impaired students on campus.",
    overview: "A wearable-camera companion app that narrates campus signage and obstacles in real time.",
    problem: "Campus wayfinding infrastructure had no support for visually impaired students.",
    solution: "Combined a lightweight object-detection model with text-to-speech for real-time narrated guidance.",
    stack: ["Computer Vision", "TTS APIs", "Python", "Swift"],
  },
};